# Generated by Django 4.2.23 on 2025-08-25 04:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('counter', 'Counter'), ('timer', 'Timer')], max_length=20)),
                ('target_value', models.FloatField(help_text='Valor objetivo del hábito')),
                ('color_hex', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color debe ser formato hex válido (#FFFFFF o #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='habits_habi_user_id_c66d7a_idx')],
            },
        ),
    ]
