# Generated by Django 5.0.2 on 2025-08-25 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color_hex',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be valid hex format (#FFFFFF or #FFF)', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')]),
        ),
        migrations.AlterField(
            model_name='habit',
            name='target_value',
            field=models.FloatField(help_text='Habit target value'),
        ),
    ]
