# Generated by Django 4.2.23 on 2025-08-25 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_workouts', models.IntegerField(default=0)),
                ('total_habits_completed', models.IntegerField(default=0)),
                ('total_calories_consumed', models.FloatField(default=0.0)),
                ('total_calories_burned', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Usuario',
                'verbose_name_plural': 'Estadísticas de Usuario',
            },
        ),
        migrations.CreateModel(
            name='WorkoutStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_duration', models.IntegerField(default=0)),
                ('total_calories_burned', models.FloatField(default=0.0)),
                ('workout_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Entrenamiento',
                'verbose_name_plural': 'Estadísticas de Entrenamientos',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NutritionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.FloatField(default=0.0)),
                ('total_protein', models.FloatField(default=0.0)),
                ('total_carbs', models.FloatField(default=0.0)),
                ('total_fat', models.FloatField(default=0.0)),
                ('total_fiber', models.FloatField(default=0.0)),
                ('meal_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estadística de Nutrición',
                'verbose_name_plural': 'Estadísticas de Nutrición',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='HabitProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('value', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='habits.habit')),
            ],
            options={
                'verbose_name': 'Progreso de Hábito',
                'verbose_name_plural': 'Progresos de Hábitos',
                'ordering': ['-date'],
                'unique_together': {('habit', 'date')},
            },
        ),
    ]
