# Generated by Django 4.2.23 on 2025-08-25 08:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('duration_min', models.PositiveIntegerField(help_text='Duración en minutos', validators=[django.core.validators.MinValueValidator(1)])),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia en kilómetros', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calories', models.PositiveIntegerField(help_text='Calorías quemadas', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('skipped', 'Skipped')], default='pending', help_text='Estado del entrenamiento', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='habits.habit')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['habit', '-date'], name='workouts_wo_habit_i_36ea35_idx'), models.Index(fields=['date'], name='workouts_wo_date_44757a_idx'), models.Index(fields=['status'], name='workouts_wo_status_66f5ca_idx')],
            },
        ),
    ]
