# Generated by Django 4.2.23 on 2025-08-25 08:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del ejercicio', max_length=200)),
                ('sets', models.PositiveIntegerField(default=1, help_text='Número de series')),
                ('reps', models.PositiveIntegerField(blank=True, help_text='Repeticiones por serie', null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Peso en kilogramos', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duración en segundos (para ejercicios de tiempo)', null=True)),
                ('rest_seconds', models.PositiveIntegerField(blank=True, help_text='Tiempo de descanso en segundos', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['workout'], name='workouts_ex_workout_8731a1_idx'), models.Index(fields=['name'], name='workouts_ex_name_5d1c33_idx')],
            },
        ),
    ]
