# Generated by Django 5.0.2 on 2025-08-25 05:44

from decimal import Decimal

import django.db.models.deletion
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
        ("workouts", "0002_exercise"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                (
                    "duration_min",
                    models.PositiveIntegerField(
                        help_text="Duración en minutos",
                        validators=[MinValueValidator(1)],
                    ),
                ),
                (
                    "distancia_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distancia en kilómetros",
                        max_digits=6,
                        null=True,
                        validators=[MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "calories",
                    models.PositiveIntegerField(
                        help_text="Calorías quemadas",
                        validators=[MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Estado del entrenamiento",
                        max_length=10,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Notas adicionales"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="habits.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
