# Generated by Django 5.0.2 on 2025-08-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_auto_20250825_0544"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
