# Generated by Django 5.0.2 on 2025-08-25 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20250825_0549'),
    ]

    operations = [
        # First, update any NULL created_at values with current timestamp
        migrations.RunSQL(
            "UPDATE workouts_exercise SET created_at = NOW() "
            "WHERE created_at IS NULL;",
            reverse_sql=""
        ),
        # Then make the field non-nullable
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, 
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        # Update any NULL updated_at values
        migrations.RunSQL(
            "UPDATE workouts_exercise SET updated_at = NOW() "
            "WHERE updated_at IS NULL;",
            reverse_sql=""
        ),
        # Make updated_at non-nullable
        migrations.AlterField(
            model_name='exercise',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, 
                default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
