# Generated by Django 5.0.2 on 2025-08-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_color_hex_alter_habit_target_value'),
        ('workouts', '0005_auto_20250825_0952'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['habit', '-date'], name='workouts_wo_habit_i_36ea35_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['date'], name='workouts_wo_date_44757a_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['status'], name='workouts_wo_status_66f5ca_idx'),
        ),
    ]
