# Generated by Django 4.2.23 on 2025-08-24 19:26

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(help_text='Nombre del alimento', max_length=200)),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein_g', models.DecimalField(decimal_places=2, help_text='Proteína en gramos', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('carbs_g', models.DecimalField(decimal_places=2, help_text='Carbohidratos en gramos', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fat_g', models.DecimalField(decimal_places=2, help_text='Grasa en gramos', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Entry',
                'verbose_name_plural': 'Nutrition Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', '-date'], name='nutrition_n_user_id_7a21a2_idx'), models.Index(fields=['date'], name='nutrition_n_date_b73435_idx')],
            },
        ),
    ]
