name: fittracker_app
description: "A comprehensive fitness tracking application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.3.1

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Navigation
  go_router: ^16.2.0

  # HTTP & API
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.8.1

  # Authentication & Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1

  # Charts & Analytics
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.2.6+1

  # Date & Time
  intl: ^0.20.2
  table_calendar: ^3.0.9

  # Forms & Input
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  image_picker: ^1.0.4

  # Utilities
  uuid: ^4.2.1
  permission_handler: ^12.0.1
  url_launcher: ^6.2.2
  package_info_plus: ^8.3.1
  device_info_plus: ^11.5.0

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^10.0.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/

  fonts:
    - family: TheSeasons
      fonts:
        - asset: assets/fonts/Fontspring-DEMO-theseasons-reg.otf
        - asset: assets/fonts/Fontspring-DEMO-theseasons-bd.otf
          weight: 700
        - asset: assets/fonts/Fontspring-DEMO-theseasons-it.otf
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-theseasons-bdit.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-theseasons-lt.otf
          weight: 300
        - asset: assets/fonts/Fontspring-DEMO-theseasons-ltit.otf
          weight: 300
          style: italic
