name: fittracker_app
description: A comprehensive fitness tracking application built with Flutter.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Navigation
  go_router: ^13.2.0

  # HTTP Client
  dio: ^5.4.0

  # UI Components
  cupertino_icons: ^1.0.6

  # Local Storage
  shared_preferences: ^2.2.2

  # Authentication
  flutter_secure_storage: ^9.0.0

  # Date and Time
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
