name: fittracker_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # 📂 Recursos de la app
  assets:
    - assets/images/
    - assets/icons/

  # 🔤 Fuentes personalizadas
  fonts:
    - family: TheSeasons
      fonts:
        - asset: assets/fonts/Fontspring-DEMO-theseasons-lt.otf
          weight: 300
        - asset: assets/fonts/Fontspring-DEMO-theseasons-ltit.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-theseasons-reg.otf
          weight: 400
        - asset: assets/fonts/Fontspring-DEMO-theseasons-it.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Fontspring-DEMO-theseasons-bd.otf
          weight: 700
        - asset: assets/fonts/Fontspring-DEMO-theseasons-bdit.otf
          weight: 700
          style: italic